In [2]:
import numpy as np

Problem 1:

In [13]:
def dot_prod():
    A = np.array([[3, -1, 4],[1, 5, -9]])
    B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
    return np.dot(A, B)

In [14]:
matrix_mult()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2:

In [233]:
def poly():
    A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
    A2 = A @ A
    A3 = A2 @ A
    return (-A3 + 9*A2 - 15*A)

In [234]:
poly()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3:

In [67]:
def array_creation():
    A = np.triu(np.ones((7, 7)))
    B1 = np.tril(np.full((7, 7), -1.))
    B2 = np.triu(np.full((7, 7), 5.))
    B = B1 + B2
    np.fill_diagonal(B, -1)
    ABA = A @ B @ A
    
    return ABA.astype(np.int64)

In [68]:
array_creation()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4:

In [71]:
def replace_neg(A):
    mask = A < 0
    A[mask] = 0
    return A

In [72]:
replace_neg(array_creation())

array([[ 0,  0,  0,  8, 25, 48, 77],
       [ 0,  0,  0,  0,  6, 24, 48],
       [ 0,  0,  0,  0,  0,  6, 25],
       [ 0,  0,  0,  0,  0,  0,  8],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

Problem 5:

In [147]:
def stacking():
    #building individual matrices
    A = np.arange(6).reshape(2, 3)
    B = np.tril(np.full((3,3), 3.))
    C = -2*np.eye(3)
    
    #creating block rows
    R1 = np.hstack((np.zeros((3, 3)), A.T, np.eye(3)))
    R2 = np.hstack((A, np.zeros((2, 3)), np.zeros((2, 2))))
    R3 = np.hstack((B, np.zeros((3, 2)), C))
    
    #combining rows
    mat = np.vstack((R1, R2, R3))
    
    return mat.astype(np.int64)

In [148]:
stacking()

array([[ 0,  0,  0,  0,  3,  1,  0,  0],
       [ 0,  0,  0,  1,  4,  0,  1,  0],
       [ 0,  0,  0,  2,  5,  0,  0,  1],
       [ 0,  1,  2,  0,  0,  0,  0,  0],
       [ 3,  4,  5,  0,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0, -2]])

Problem 6:

In [191]:
def make_row_stoch(A):
    x = A.sum(axis=1).reshape((3, 1))
    return (A / x)

Problem 7:

In [223]:
def greatest_prod():
    #load the grid
    grid = np.load(r"/Users/Walker/Desktop/OSM/BootCamp2017/Computation/Wk1_PyIntro/grid.npy")
    
    #horizontal max
    max_hor = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    
    #vertical max
    max_ver = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    
    #diagonal maximums (left and right)
    max_rdiag = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    max_ldiag = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
    
    return max(max_hor, max_ver, max_rdiag, max_ldiag)
    

In [224]:
greatest_prod()

70600674